---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Install haproxy
  ansible.builtin.package:
    name:
      - "haproxy"
    state: present

- name: Ensure haproxy systemd drop-in directory
  ansible.builtin.file:
    path: /etc/systemd/system/haproxy.service.d
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Install haproxy systemd drop-in
  ansible.builtin.template:
    src: etc/systemd/system/haproxy.service.d/override.conf.j2
    dest: /etc/systemd/system/haproxy.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart haproxy

- name: Install haproxy configuration for LB servers
  ansible.builtin.template:
    src: etc/haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload haproxy

- name: Enable and start haproxy
  ansible.builtin.service:
    name: haproxy
    enabled: true
    state: started

- name: Enable firewalld rule for port 8080
  ansible.posix.firewalld:
    port: 8080/tcp
    state: enabled
    permanent: true
    immediate: true
