---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload haproxy
  ansible.builtin.service:
    name: haproxy
    state: reloaded

- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
